### ISSUE TITLE
Import to eclipse from zip file

### ISSUE THREAD

**Issue by ahmads1** [StevenRudenko/BleSensorTag#3]
Hello Steven and all the others,

I recently just downloaded your BleSensorTag project. 
Now I want to import it into Eclipse ADT but I just can't.
It doesn't find the file when I choose "Existing Projects into Workspace" and then "Select archive file".

I need your help urgently!

Thanks in advance for any kind of help.

**Comment by StevenRudenko** [comment]
nobody uses Eclipse anymore
