### ISSUE TITLE
I can't get the device Name

### ISSUE THREAD

**Issue by Fakher-Hakim** [StevenRudenko/BleSensorTag#6]
In fact, the function that return the name of the device in never used.
the function is :
@Override
            public void onLeScan(BluetoothDevice device, int rssi, byte[] scanRecord) {
                Log.d(TAG, "Device discovered: " + device.getName());
                Log.e("MY_TAG",device.getName());
                if (RECORD_DEVICE_NAME.equals(RECORD_DEVICE_NAME)) {
                    scanner.stop();
                    getBleManager().connect(getBaseContext(), device.getAddress());
                }
            }
in class "BleSensorsRecordService"

**Comment by StevenRudenko** [comment]
in fact `onLeScan` is called by `bluetoothAdapter.startLeScan()`. device name can be null though.

also you have an useless check in your function: `if (RECORD_DEVICE_NAME.equals(RECORD_DEVICE_NAME))`
