### ISSUE TITLE
Connecting but no sensor data just "Unknown"

### ISSUE THREAD

**Issue by jahangirkabir** [StevenRudenko/BleSensorTag#8]
No sensor data is showing just showing "Unknown", but works well with Official Application
![device-2017-01-19-133847](https://cloud.githubusercontent.com/assets/826791/22097762/f27e7f60-de4c-11e6-9183-769bc26d9852.png)
![device-2017-01-19-134056](https://cloud.githubusercontent.com/assets/826791/22097761/f27a2f82-de4c-11e6-99c4-5254184f2628.png)

**Comment by StevenRudenko** [comment]
@jahangirkabir the only thing you needed to do is to add device support to `DeviceDefCollection` based on `CC2650 SensorTag` device name

**Comment by StevenRudenko** [comment]
I've added it with last push. Please note that new version of SensorTag has a bit different BLE stack so not all sensors will be detected
